name: agenda_phone_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^9.2.2
  path: ^1.8.3  
  crypto: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
